language: julia

notifications:
  email: false

julia:
- 1
- nightly
- 1.6
- 1.5
- 1.4
- 1.3
- 1.2
- 1.1
- 1.0

os:
- linux
- osx
- windows

env:
- PYTHONJL_EXE=CONDA

codecov: true

jobs:
  allow_failures:
    - julia: nightly
  fast_finish: true
  include:
    - name: documentation
      script:
        - julia --project=docs/ -e 'using Pkg; Pkg.develop(PackageSpec(path=pwd())); Pkg.instantiate()'
        - julia --project=docs/ docs/make.jl
      after_success: skip
