language: julia

os: linux

notifications:
  email: false

julia:
- 1
- 1.5
- 1.4
- 1.3
- 1.2
- 1.1
- 1.0

env:
- PYTHONJL_EXE=CONDA

codecov: true

jobs:
  include:
    - stage: "Documentation"
      julia: 1
      os: linux
      script:
        - julia --project=docs/ -e 'using Pkg; Pkg.develop(PackageSpec(path=pwd())); Pkg.instantiate()'
        - julia --project=docs/ docs/make.jl
      after_success: skip
